// 개발 일지 데이터. 단계가 끝날 때마다 맨 아래에 항목을 추가하고 `npm run build`로 .docx를 다시 만든다.
// 키·Secret 같은 비밀 값은 절대 적지 않는다 (값이 아니라 "어디서 관리하는지"만 적는다).
//
// 항목 형식
//   id, title, date, status: '완료' | '진행 중' | '결정 대기'
//   commits: [커밋 해시]
//   goal: 이 단계의 목표 (한 문장)
//   work: [한 일]
//   problems: [{ problem, cause, solution, status: '해결' | '미해결' | '결정 대기' | '확인 필요' }]
//   decisions: [이 단계에서 확정된 결정·가정]
//   pending: [남은 일 / 사용자 결정이 필요한 것]

module.exports = [
  {
    id: 1,
    title: '골격: 디자인 토큰·공통 컴포넌트·도메인·Mock·라우터',
    date: '2026-10-04',
    status: '완료',
    commits: ['70fac67'],
    goal: '화면을 올릴 수 있는 앱 뼈대와, API 없이도 개발할 수 있는 Mock 구조를 만든다.',
    work: [
      '디자인 토큰(AppColors/Typography/Spacing/Radius/Shadow)과 테마',
      '공통 위젯: 버튼, 헤더/StepHeader, 입력, 칩, 카드, Loading/Empty/Error 상태, 시트/모달, 지도 미리보기(AptMap)',
      '도메인 모델 + Repository 인터페이스 (auth/saved/place/extraction/home/course/party/preference/my)',
      'Mock Repository(지연·빈 응답·오류 시나리오) + Api* 스텁(NEEDS BACKEND)',
      'go_router: 하단 5탭 + 인증 redirect, Android 공유 수신(ACTION_SEND) + 비로그인 시 pendingShare 보관',
    ],
    problems: [
      {
        problem: '이 커밋만으로는 빌드되지 않음',
        cause: '라우터가 아직 작성하지 않은 화면 파일을 참조',
        solution: '2단계에서 구현된 화면만 연결하고 나머지는 임시 화면으로 채워 빌드 가능 상태로 복구',
        status: '해결',
      },
    ],
    decisions: [
      '데이터 흐름: DTO → mapper → Domain → Provider → Widget (Widget에서 JSON 직접 참조 금지)',
      'API 명세 전까지 USE_MOCK=true 기본, MOCK_SCENARIO(normal/empty/error)로 상태 UI 검증',
    ],
    pending: [],
  },
  {
    id: 2,
    title: '인증 화면 (#1–#8)',
    date: '2026-10-04',
    status: '완료',
    commits: ['c49b750'],
    goal: '소셜 로그인 기본, 이메일 로그인은 틀만 있는 가입·로그인 흐름을 만든다.',
    work: [
      '#1 소셜 로그인, #2 약관 동의, #3 프로필 설정(닉네임 인라인 검증), #4 가입 완료',
      '#5 계정 충돌, #6 소셜 인증 오류',
      '#7/#8 이메일 로그인 틀 (FeatureFlags.emailAuthEnabled=false, 진입점 숨김)',
      '단위 테스트: 인증 redirect, 인스타그램 URL 파싱, 포매터/D-day, CourseDraft',
    ],
    problems: [
      {
        problem: '인증 API 명세가 없어 신규/기존/충돌 흐름을 확인할 방법이 없음',
        cause: '백엔드 미제공',
        solution: 'Mock에서 공급자별로 결과를 다르게 줌 (카카오=신규, Google=기존, Apple=계정 충돌)',
        status: '해결',
      },
    ],
    decisions: ['이메일 로그인은 flag off 상태로 화면 진입점 노출 금지'],
    pending: ['NEEDS BACKEND: 소셜 토큰 교환, 신규/기존 판별, 충돌 응답, 약관 버전, 닉네임 규칙, 토큰 갱신'],
  },
  {
    id: 3,
    title: '저장됨 · 장소 상세 · 저장 지도',
    date: '2026-10-04',
    status: '완료',
    commits: ['1dc8133', '9baf326', '35254f9', 'f3c4cff', '45d3fae', '12abcc8', 'bb72ed3', '61437c0'],
    goal: '카테고리(유형별) + 보관함(목적별) 두 축의 저장 구조와 지도 화면을 만든다.',
    work: [
      '저장됨 탭 (#13 카테고리 / #14 내 보관함), 보관함 선택 시트(#12), 새 보관함 모달(#15)',
      '보관함 상세(#17)·빈 보관함(#16), 장소 상세(#20), 저장 장소 선택기 + 장소 추가(#29)',
      '저장 지도(#18/#19): 지도 이동 → 400ms debounce → 보이는 영역(bbox) 조회, 드래그 바텀시트',
    ],
    problems: [
      {
        problem: '네이버 지도 키가 없어 실제 지도를 띄울 수 없음',
        cause: '키 미발급',
        solution: 'AptMap이 SDK 타입을 감추고, 키가 없으면 마커 배치만 보여주는 미리보기 지도를 쓰게 함',
        status: '해결',
      },
      {
        problem: '"내 위치" 버튼을 동작시킬 수 없음',
        cause: '위치 권한·지도 SDK 미도입',
        solution: '안내 문구만 표시 (13단계에서 구현)',
        status: '해결',
      },
    ],
    decisions: ['한 장소는 여러 보관함에 속할 수 있음 (Place ≠ SavedPlace)'],
    pending: ['NEEDS BACKEND: 보관함·카테고리 API(다대다, 페이지네이션, bbox 조회, 클러스터링 여부)'],
  },
  {
    id: 4,
    title: '추출 (링크 입력 · 결과 검토)',
    date: '2026-10-04',
    status: '완료',
    commits: ['006701b', '5436d10'],
    goal: '공유로 들어온 링크를 분석해 장소를 골라 저장하는 흐름을 만든다.',
    work: [
      '#10 링크 입력(폴백), #11 결과 검토: 진입 즉시 분석 자동 시작(공유 진입 포함), 단계형 로딩',
      '장소 복수 선택, 이미 저장된 장소는 선택 불가, 보관함 선택(#12)으로 이어짐',
    ],
    problems: [
      {
        problem: '추출 진행/실패/비공개/장소 없음 상태의 디자인이 없음',
        cause: '시안 미포함',
        solution: '공통 Empty/Error 컴포넌트로 임시 구현하고 사용자에게 알림',
        status: '해결',
      },
      {
        problem: '추출 API가 동기인지 비동기(작업 ID + 폴링)인지 모름',
        cause: '명세 없음',
        solution: 'Repository 내부에서 흡수하도록 인터페이스를 설계, 화면은 단계형 로딩만 표시',
        status: '확인 필요',
      },
    ],
    decisions: [],
    pending: ['NEEDS BACKEND: 추출 API 방식, 진행 상태, 실패 사유 코드'],
  },
  {
    id: 5,
    title: '홈 대시보드',
    date: '2026-10-04',
    status: '완료',
    commits: ['21159e9', '9114882'],
    goal: '저장·코스·추출 현황과 최근 추출, 지금 뜨는 장소를 보여준다.',
    work: ['홈(#9): 통계 카드, 최근 추출한 장소, 지금 뜨는 장소'],
    problems: [
      {
        problem: '통계 숫자를 어디서 가져올지 미정',
        cause: '홈 aggregate API 명세 없음',
        solution: '프론트에서 목록을 받아 세지 않고 서버 aggregate 값을 표시하도록 설계 (Mock 값 사용)',
        status: '확인 필요',
      },
    ],
    decisions: ['카테고리·통계·추천 비율은 하드코딩하지 않고 서버 값을 표시'],
    pending: ['NEEDS BACKEND: 홈 aggregate / 트렌딩 API'],
  },
  {
    id: 6,
    title: '코스 · 파티 · AI 추천 루프',
    date: '2026-10-04',
    status: '완료',
    commits: ['719cbd0', '20b221b', '72fe587', 'b09d483', 'fa11aec', 'dc5f618', '03e630d', 'b523660', '9059219', '655f228', 'e5b0459'],
    goal: '정보 → 장소 → 동행 → AI 추천(수정 ↔ 재추천 반복)으로 코스를 만드는 위저드를 만든다.',
    work: [
      '코스 목록(#22)·빈 상태(#21), 위저드 1/4 기본 정보(#23), 2/4 장소 선택(#24), 3/4 동행(#25/#26)',
      '4/4 AI 추천·동선 검토(#30): 선택 장소(파랑 번호) vs AI 추천(주황 ✦ + 이유), 점수 미노출',
      '항목 편집(순서·교체·빼기·추가), 다른 추천(이전 결과 유지 + 실패 시 복구)',
      '코스 완료(#31), 상세·관리(#32), 파티 초대 모달(#27), 초대 수락(#28)',
    ],
    problems: [
      {
        problem: '재추천의 의미(AI 장소만 교체 vs 전체 재생성)와 제외 목록 지원 여부를 모름',
        cause: '추천 API 명세 없음',
        solution: 'CourseDraft에 사용자가 뺀 AI 추천을 기록해 두고, 재추천 실패 시 이전 결과로 복구',
        status: '확인 필요',
      },
    ],
    decisions: ['위저드는 하나의 CourseDraft 공유, 진행 바는 4/4 유지(새 단계 만들지 않음)'],
    pending: ['NEEDS BACKEND: 코스 CRUD, 추천/재추천 API, 초대 링크·만료·인원 초과 에러'],
  },
  {
    id: 7,
    title: '마이 · 취향 설정',
    date: '2026-10-04',
    status: '완료',
    commits: ['ab6e525', 'aeb334e', 'c079884'],
    goal: '마이 화면과 취향 설정을 만들고 임시 화면을 정리한다.',
    work: ['취향 설정(#34), 마이(#33)', '사용하지 않는 임시 화면(ComingSoonPage) 삭제'],
    problems: [],
    decisions: [],
    pending: ['NEEDS BACKEND: 취향 키워드 체계, 내 프로필·통계 aggregate'],
  },
  {
    id: 8,
    title: '폴리시 · 테스트',
    date: '2026-10-04',
    status: '완료',
    commits: ['e03de9a', 'feeb576', 'fc28b58', 'f532e8c', '5fd3530'],
    goal: '여러 기기 크기와 실제 에뮬레이터에서 화면·흐름을 검증한다.',
    work: [
      '화면 스모크 테스트: 360×640 / 390×844 / 430×932에서 overflow·예외 검사',
      '통합 테스트: 에뮬레이터(API 36)에서 주요 사용자 흐름 10개 — 10/10 통과',
      '에뮬레이터에서 공유 수신(콜드/웜 스타트, 비로그인 보류 후 재개) 실제 동작 확인',
    ],
    problems: [
      { problem: '저장됨 카테고리 그리드가 작은 기기에서 잘림', cause: '비율 기반 높이', solution: '높이 고정', status: '해결' },
      { problem: '장소 상세의 긴 링크 라벨이 360 폭에서 넘침', cause: 'AppTextLink 줄바꿈 없음', solution: '말줄임 처리', status: '해결' },
      {
        problem: '지도 미리보기에서 핀이 한 점으로 뭉침',
        cause: '멀리 떨어진 장소 하나 때문에 영역이 넓어짐',
        solution: '밀집 지역 기준으로 영역 계산, 영역 밖 핀은 숨김',
        status: '해결',
      },
      { problem: '지도 핀이 상단 검색바·칩에 가려짐', cause: '가려지는 영역 미고려', solution: 'topPadding 추가', status: '해결' },
      { problem: '홈 최근 추출의 "저장됨"이 비활성 버튼처럼 보임', cause: '버튼 스타일 사용', solution: '상태 태그로 표시', status: '해결' },
      { problem: 'CLAUDE.md의 디자인 시안 경로가 실제와 다름', cause: '폴더 위치 변경', solution: 'design/ui/ 로 수정', status: '해결' },
    ],
    decisions: [],
    pending: [],
  },
  {
    id: 9,
    title: '외부 연동 점검 (소셜 로그인 · 네이버 지도)',
    date: '2026-10-04',
    status: '완료',
    commits: [],
    goal: '실제 연동을 위해 코드베이스에서 부족한 부분을 확인한다.',
    work: [
      '소셜: 화면·인터페이스(SocialAuthProvider)는 있으나 SDK 패키지·네이티브 설정·키 없음, ApiAuthRepository 미구현',
      '지도: AptMap 추상화는 있으나 flutter_naver_map 미도입, 실제 지도 위젯 없음',
      '패키지명이 com.example.apt — 키가 패키지명에 묶이므로 먼저 확정 필요',
    ],
    problems: [],
    decisions: ['소셜 로그인 진행 방식 A 제안: SDK만 먼저 붙이고 서버 토큰 교환은 Mock 유지'],
    pending: [],
  },
  {
    id: 10,
    title: '네이버 지도 SDK 도입 + 지도 위젯 골격',
    date: '2026-10-04',
    status: '완료',
    commits: ['ed0fbe5'],
    goal: '키만 넣으면 실제 지도가 뜨도록 SDK 구현을 AptMap 뒤에 붙인다 (화면 코드는 그대로).',
    work: [
      'flutter_naver_map 1.4.4 도입, main에서 NAVER_MAP_CLIENT_ID로 초기화(NaverMapSdk)',
      'NaverMapView: 기존 MapPin 위젯을 마커 이미지로 사용, 경로선, 최초 카메라 맞춤, 보이는 영역 콜백',
      '미리보기 지도를 별도 파일로 분리, AptMap은 SDK 준비 여부에 따라 분기',
    ],
    problems: [
      {
        problem: '저장 지도에서 마커가 바뀔 때마다 카메라를 맞추면 지도가 계속 끌려감',
        cause: '지도 이동 → 영역 조회 → 마커 변경 → 카메라 이동의 순환',
        solution: '영역 기반 화면은 처음 한 번만 카메라를 맞추고, 이후엔 사용자 조작을 따름',
        status: '해결',
      },
      {
        problem: '선택 변경 시 마커를 전부 지우고 다시 그려 깜빡일 수 있음',
        cause: '오버레이 전체 교체 방식',
        solution: '마커가 많아지면 id 기준 변경분만 갱신하도록 개선 (TODO)',
        status: '미해결',
      },
    ],
    decisions: ['키가 없거나 인증에 실패하면 미리보기 지도로 자동 폴백', '`© NAVER` 로고는 숨기지 않음'],
    pending: [],
  },
  {
    id: 11,
    title: '패키지명 확정 · 소셜 로그인 SDK 연동 · Apple 제외',
    date: '2026-10-05',
    status: '완료',
    commits: ['416c0c4', '003a5df'],
    goal: '키 발급 전제를 갖추고, 키만 넣으면 카카오/Google 실로그인이 되게 한다.',
    work: [
      '패키지명/Bundle ID: com.teamjkk.apt (Android/iOS/Windows 리소스)',
      'SdkSocialAuthProvider: 키가 있는 공급자만 실제 SDK, 없으면 Mock SDK. 취소/실패 구분',
      'Android: dart-define 값으로 카카오 리다이렉트 scheme 자동 생성. iOS: Info.plist URL scheme + Secrets.xcconfig',
      '키 관리: config/dev.json(--dart-define-from-file), ios/Flutter/Secrets.xcconfig — 둘 다 gitignore, 예시 파일만 커밋',
      '디버그 키 해시(카카오)와 SHA-1(Google) 추출해 전달',
    ],
    problems: [
      {
        problem: 'Apple 로그인 구현 불가',
        cause: 'Apple Developer Program 유료 멤버십 필요',
        solution: 'FeatureFlags.appleAuthEnabled=false로 iOS/Android 모두 버튼 숨김 (코드는 유지)',
        status: '해결',
      },
      {
        problem: '계정 충돌 통합 테스트가 Apple 버튼에 의존',
        cause: 'Mock에서 충돌 시나리오가 Apple에 연결됨',
        solution: '라우터로 충돌 화면에 직접 진입하도록 테스트 수정',
        status: '해결',
      },
      {
        problem: 'Gradle 스크립트 컴파일 오류 (java.util.Base64 인식 실패)',
        cause: 'build.gradle.kts 안에서 `java`가 Gradle 확장으로 해석됨',
        solution: '파일 상단에 import java.util.Base64 추가',
        status: '해결',
      },
      {
        problem: '커밋 416c0c4 단독으로는 Android 빌드 불가',
        cause: 'Gradle의 패키지명 변경이 다음 커밋(003a5df)에 포함됨',
        solution: '현재 main은 정상. 이후 커밋은 단독 빌드 가능 단위로 나눔',
        status: '해결',
      },
    ],
    decisions: [
      '패키지명 com.teamjkk.apt 확정',
      'Apple 로그인은 유료 멤버십 전까지 제외',
      '소셜 로그인 방식 A (SDK 먼저, 서버 교환은 Mock)',
      '서버로 보낼 토큰 가정: 카카오 access token, Google idToken (서버 확정 필요)',
    ],
    pending: ['카카오 네이티브 앱 키, Google 웹/iOS 클라이언트 ID 발급', 'NEEDS BACKEND: 서버가 받을 소셜 토큰 종류 확정'],
  },
  {
    id: 12,
    title: '저장 지도 "내 위치"',
    date: '2026-10-05',
    status: '완료',
    commits: ['2510548'],
    goal: '네이버 지도에서 내 위치로 이동·추적할 수 있게 한다.',
    work: [
      'AptMapController.showMyLocation(): 화면은 SDK를 모른 채 명령만 보냄',
      'SDK 기본 위치 추적기 사용, 권한 거부/영구 거부 시 안내 문구',
      '권한 선언: Android FINE/COARSE, iOS NSLocationWhenInUseUsageDescription',
    ],
    problems: [],
    decisions: ['위치는 앱 사용 중에만 사용 (백그라운드 위치 미사용)'],
    pending: [],
  },
  {
    id: 13,
    title: '네이버 지도 키 적용 · 에뮬레이터 실검증',
    date: '2026-10-05',
    status: '완료',
    commits: ['fc3be3e'],
    goal: '실제 Client ID로 지도 인증과 마커·영역 조회·내 위치 동작을 확인한다.',
    work: [
      'Client ID를 config/dev.json에만 저장 (gitignore 확인, 저장소·이력에 값 없음 확인)',
      '에뮬레이터(Android 16)에서 지도 인증 통과, 마커 탭 → 라벨·카드 선택, 영역 조회, 내 위치(정확한 위치) 확인',
    ],
    problems: [
      {
        problem: 'Client Secret을 어디에 쓰는지',
        cause: '5개 API(지도/Directions 5·15/Geocoding/Reverse Geocoding) 키를 함께 받음',
        solution: '앱은 Dynamic Map Client ID만 사용. Secret은 서버의 REST 호출용이라 레포·앱에 저장하지 않음. 대화에 노출되어 재발급 권고',
        status: '해결',
      },
      {
        problem: 'NAVER 로고·축척이 화면 위쪽에 표시됨',
        cause: '하단 여백을 contentPadding과 logoMargin에 이중으로 적용',
        solution: 'logoMargin 제거 (contentPadding 기준으로 배치)',
        status: '해결',
      },
      {
        problem: '멀리 떨어진 장소 하나 때문에 나머지 장소가 한 점으로 뭉쳐 보임',
        cause: '실제 지도는 모든 점을 포함하도록 카메라를 맞춤',
        solution: '미리보기 지도의 밀집 지역 계산(focusBounds)을 공유해 실제 지도에도 적용',
        status: '해결',
      },
      {
        problem: '에뮬레이터 앱 설치 실패 (INSUFFICIENT_STORAGE)',
        cause: '에뮬레이터 저장 공간 87% 사용',
        solution: '캐시 정리 후 재설치 (재설치로 권한 초기화됨)',
        status: '해결',
      },
      {
        problem: '"대략적 위치"를 허용하면 내 위치가 뜨지 않음',
        cause: 'SDK 기본 추적기가 Android에서 정확한 위치 권한만 확인',
        solution: 'geolocator 기반 위치 추적기로 교체 제안 (15단계 참고)',
        status: '결정 대기',
      },
      {
        problem: '권한 허용 직후 첫 탭에서 지도가 이동하지 않음 (두 번째 탭에서 이동)',
        cause: '첫 위치를 받지 못하면 SDK가 추적을 실패로 끝냄 — 에뮬레이터 위치 신호 지연 추정',
        solution: '실기기에서 재확인, geolocator 도입 시 대기 시간 직접 제어',
        status: '확인 필요',
      },
    ],
    decisions: ['네이버 Secret은 서버에서만 관리 (Directions·Geocoding은 서버 책임)'],
    pending: ['백엔드 팀에 Secret 전달(재발급 후), Directions 5/15 선택은 코스 최대 장소 수 기준'],
  },
  {
    id: 14,
    title: '위치 권한 상세 분석',
    date: '2026-10-05',
    status: '결정 대기',
    commits: [],
    goal: '권한 상황별 동작과 빈틈을 정리하고 해결 방법을 정한다.',
    work: [
      '상황별 동작 정리: 정확한 위치 ✅ / 대략적 위치 ❌ / 거부·영구 거부 안내 / iOS 거부 / GPS 꺼짐 / 미리보기 지도',
      'SDK 코드 확인: Android는 FINE만 확인, iOS는 거부(.denied)를 일반 거부로 전달, 위치 서비스 꺼짐 확인 없음',
    ],
    problems: [
      { problem: '대략적 위치 허용 시 동작 안 함', cause: 'SDK가 FINE 권한만 확인', solution: 'geolocator로 위치 추적기 직접 구현', status: '결정 대기' },
      {
        problem: 'iOS에서 한 번 거부하면 다시 물어볼 수 없는데 "허용하면…" 문구가 뜸',
        cause: 'SDK가 iOS 거부를 일반 거부로 전달',
        solution: 'geolocator로 영구 거부를 플랫폼별로 정확히 구분',
        status: '결정 대기',
      },
      { problem: 'GPS(위치 서비스)가 꺼져 있을 때 처리 없음', cause: 'SDK에 확인 로직 없음', solution: '위치 서비스 확인 + 위치 설정 열기', status: '결정 대기' },
      { problem: '영구 거부 시 설정 화면으로 보낼 수 없음', cause: '설정 열기 기능 없음', solution: 'geolocator의 앱 설정 열기 사용', status: '결정 대기' },
    ],
    decisions: ['앞서 제안한 permission_handler는 철회 — 권한만 받아도 SDK 추적기가 여전히 FINE만 확인하므로 해결되지 않음'],
    pending: [
      'geolocator 기반 위치 추적기로 진행할지',
      '영구 거부·GPS 꺼짐 시 스낵바에 "설정 열기" 버튼을 붙일지',
      '권한 요청 전 설명 바텀시트를 만들지 (디자인 없음)',
      'iOS 위치 안내 문구 검토 (App Store 심사 대상)',
    ],
  },
  {
    id: 15,
    title: '개발 일지(.docx) 체계 도입',
    date: '2026-10-05',
    status: '완료',
    commits: [],
    goal: '개발 과정·문제·해결 방법을 단계마다 프로젝트 폴더의 Word 문서로 남긴다.',
    work: [
      'tools/devlog/entries.js(기록 데이터) + build_devlog.js(생성기) → docs/08_DEV_LOG.docx',
      '생성 도구는 앱과 분리된 Node 도구 (docx 패키지, node_modules는 gitignore)',
      '1–14단계를 git 이력과 작업 기록으로 소급 작성',
    ],
    problems: [
      {
        problem: '1–8단계의 세부 문제는 이전 세션 기록이 없어 커밋 메시지 기준으로만 작성됨',
        cause: '일지 도입 전 단계',
        solution: '커밋 본문에 남은 문제·해결만 기록, 이후 단계부터는 진행 중 바로 기록',
        status: '해결',
      },
    ],
    decisions: ['단계가 끝날 때마다 entries.js에 추가하고 .docx를 다시 생성해 함께 커밋', '비밀 값은 일지에 적지 않음'],
    pending: [],
  },
];
